### ISSUE TITLE
Components are duplicated in the deploy folder

### ISSUE THREAD

**Issue by darraghjones** [dapr/generator-dapr#19]
When I run `yo dapr` the resulting folder structure has two subfolders named components and deploy. The redis-store.yaml, redis-pubsub.yaml, etc. are created in both of these folders.

The yeoman generator also prints: 

> Next you'll need to create a Redis store and add configuration details to your redis.yaml

But which one? It's super confusing.

I'm kind of guessing this is to support both dapr cli, and k8s deployment modes? 
It seems like the component files should just be in the components folder, with the other microservice objects in the deploy folder.

**Comment by ryanvolum** [comment]
Hey @darraghjones, you guessed right, and this is temporary. I make a note of this in each of the readmes for the microservices, but it's a bit buried: 

> Note that the dapr cli will automatically configure a Redis store and Redis pubsub component, with component manifests in a "components" directory (redis.yaml and redis_messagebus.yaml respectively). If you selected non-Redis components (e.g. Cosmos, NATS) that you want to run in self-hosted mode, copy the generated components directory into your microservice's directory. dapr run will look for the components directory and use the components specified there instead of Redis if found. This step will no longer be necessary when [Issue 225](https://github.com/dapr/cli/issues/225) is resolved.

Basically, once issue 225 is resolved, we'll be removing the `components` folder altogether and pointing to the `deploy` folder when running `dapr run`.
